### ISSUE TITLE
Change name of assessment folder

### ISSUE THREAD

**Issue by feliciahou** [BCIT-LTC/course-skeleton#1]
We met with Marlena this morning to discuss a standard way of storing images for quizzes (where to store them). There was some confusion about what the Assessments folder in the skeleton should be used for. Some other name ideas included quiz-images, quiz-assets, question-assets, QuizMedia, etc. After some discussion, we agreed on using assessment-assets and Marlena will bring this to the ETS meeting.

**Comment by kphunter** [comment]
This should have been closed automatically by #2
